// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: efgs.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReportType int32

const (
	ReportType_UNKNOWN                      ReportType = 0
	ReportType_CONFIRMED_TEST               ReportType = 1
	ReportType_CONFIRMED_CLINICAL_DIAGNOSIS ReportType = 2
	ReportType_SELF_REPORT                  ReportType = 3
	ReportType_RECURSIVE                    ReportType = 4
	ReportType_REVOKED                      ReportType = 5
)

// Enum value maps for ReportType.
var (
	ReportType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONFIRMED_TEST",
		2: "CONFIRMED_CLINICAL_DIAGNOSIS",
		3: "SELF_REPORT",
		4: "RECURSIVE",
		5: "REVOKED",
	}
	ReportType_value = map[string]int32{
		"UNKNOWN":                      0,
		"CONFIRMED_TEST":               1,
		"CONFIRMED_CLINICAL_DIAGNOSIS": 2,
		"SELF_REPORT":                  3,
		"RECURSIVE":                    4,
		"REVOKED":                      5,
	}
)

func (x ReportType) Enum() *ReportType {
	p := new(ReportType)
	*p = x
	return p
}

func (x ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_efgs_proto_enumTypes[0].Descriptor()
}

func (ReportType) Type() protoreflect.EnumType {
	return &file_efgs_proto_enumTypes[0]
}

func (x ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportType.Descriptor instead.
func (ReportType) EnumDescriptor() ([]byte, []int) {
	return file_efgs_proto_rawDescGZIP(), []int{0}
}

type DiagnosisKeyBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*DiagnosisKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *DiagnosisKeyBatch) Reset() {
	*x = DiagnosisKeyBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_efgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosisKeyBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisKeyBatch) ProtoMessage() {}

func (x *DiagnosisKeyBatch) ProtoReflect() protoreflect.Message {
	mi := &file_efgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisKeyBatch.ProtoReflect.Descriptor instead.
func (*DiagnosisKeyBatch) Descriptor() ([]byte, []int) {
	return file_efgs_proto_rawDescGZIP(), []int{0}
}

func (x *DiagnosisKeyBatch) GetKeys() []*DiagnosisKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DiagnosisKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyData                    []byte     `protobuf:"bytes,1,opt,name=keyData,proto3" json:"keyData,omitempty"` // key
	RollingStartIntervalNumber uint32     `protobuf:"varint,2,opt,name=rollingStartIntervalNumber,proto3" json:"rollingStartIntervalNumber,omitempty"`
	RollingPeriod              uint32     `protobuf:"varint,3,opt,name=rollingPeriod,proto3" json:"rollingPeriod,omitempty"`                 // number of 10-minute windows between key-rolling
	TransmissionRiskLevel      int32      `protobuf:"varint,4,opt,name=transmissionRiskLevel,proto3" json:"transmissionRiskLevel,omitempty"` // risk of transmission
	VisitedCountries           []string   `protobuf:"bytes,5,rep,name=visitedCountries,proto3" json:"visitedCountries,omitempty"`
	Origin                     string     `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`                          // country of origin
	ReportType                 ReportType `protobuf:"varint,7,opt,name=reportType,proto3,enum=ReportType" json:"reportType,omitempty"` // set by backend
	DaysSinceOnsetOfSymptoms   int32      `protobuf:"zigzag32,8,opt,name=days_since_onset_of_symptoms,json=daysSinceOnsetOfSymptoms,proto3" json:"days_since_onset_of_symptoms,omitempty"`
}

func (x *DiagnosisKey) Reset() {
	*x = DiagnosisKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_efgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosisKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisKey) ProtoMessage() {}

func (x *DiagnosisKey) ProtoReflect() protoreflect.Message {
	mi := &file_efgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisKey.ProtoReflect.Descriptor instead.
func (*DiagnosisKey) Descriptor() ([]byte, []int) {
	return file_efgs_proto_rawDescGZIP(), []int{1}
}

func (x *DiagnosisKey) GetKeyData() []byte {
	if x != nil {
		return x.KeyData
	}
	return nil
}

func (x *DiagnosisKey) GetRollingStartIntervalNumber() uint32 {
	if x != nil {
		return x.RollingStartIntervalNumber
	}
	return 0
}

func (x *DiagnosisKey) GetRollingPeriod() uint32 {
	if x != nil {
		return x.RollingPeriod
	}
	return 0
}

func (x *DiagnosisKey) GetTransmissionRiskLevel() int32 {
	if x != nil {
		return x.TransmissionRiskLevel
	}
	return 0
}

func (x *DiagnosisKey) GetVisitedCountries() []string {
	if x != nil {
		return x.VisitedCountries
	}
	return nil
}

func (x *DiagnosisKey) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *DiagnosisKey) GetReportType() ReportType {
	if x != nil {
		return x.ReportType
	}
	return ReportType_UNKNOWN
}

func (x *DiagnosisKey) GetDaysSinceOnsetOfSymptoms() int32 {
	if x != nil {
		return x.DaysSinceOnsetOfSymptoms
	}
	return 0
}

var File_efgs_proto protoreflect.FileDescriptor

var file_efgs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x66, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x11,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x21, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x52, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x22, 0xf5, 0x02, 0x0a, 0x0c, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x3e, 0x0a, 0x1a, 0x72, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x1a, 0x72, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x24, 0x0a, 0x0d, 0x72, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x34, 0x0a, 0x15, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x69, 0x73, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x69, 0x73, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x76,
	0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12,
	0x2b, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x1c,
	0x64, 0x61, 0x79, 0x73, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x6f, 0x6e, 0x73, 0x65, 0x74,
	0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x79, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x11, 0x52, 0x18, 0x64, 0x61, 0x79, 0x73, 0x53, 0x69, 0x6e, 0x63, 0x65, 0x4f, 0x6e, 0x73,
	0x65, 0x74, 0x4f, 0x66, 0x53, 0x79, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x73, 0x2a, 0x7c, 0x0a, 0x0a,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4e, 0x46, 0x49,
	0x52, 0x4d, 0x45, 0x44, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x43,
	0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x45, 0x44, 0x5f, 0x43, 0x4c, 0x49, 0x4e, 0x49, 0x43, 0x41,
	0x4c, 0x5f, 0x44, 0x49, 0x41, 0x47, 0x4e, 0x4f, 0x53, 0x49, 0x53, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x45, 0x4c, 0x46, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x03, 0x12, 0x0d,
	0x0a, 0x09, 0x52, 0x45, 0x43, 0x55, 0x52, 0x53, 0x49, 0x56, 0x45, 0x10, 0x04, 0x12, 0x0b, 0x0a,
	0x07, 0x52, 0x45, 0x56, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0x05, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b,
	0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_efgs_proto_rawDescOnce sync.Once
	file_efgs_proto_rawDescData = file_efgs_proto_rawDesc
)

func file_efgs_proto_rawDescGZIP() []byte {
	file_efgs_proto_rawDescOnce.Do(func() {
		file_efgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_efgs_proto_rawDescData)
	})
	return file_efgs_proto_rawDescData
}

var file_efgs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_efgs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_efgs_proto_goTypes = []interface{}{
	(ReportType)(0),           // 0: ReportType
	(*DiagnosisKeyBatch)(nil), // 1: DiagnosisKeyBatch
	(*DiagnosisKey)(nil),      // 2: DiagnosisKey
}
var file_efgs_proto_depIdxs = []int32{
	2, // 0: DiagnosisKeyBatch.keys:type_name -> DiagnosisKey
	0, // 1: DiagnosisKey.reportType:type_name -> ReportType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_efgs_proto_init() }
func file_efgs_proto_init() {
	if File_efgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_efgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosisKeyBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_efgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosisKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_efgs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_efgs_proto_goTypes,
		DependencyIndexes: file_efgs_proto_depIdxs,
		EnumInfos:         file_efgs_proto_enumTypes,
		MessageInfos:      file_efgs_proto_msgTypes,
	}.Build()
	File_efgs_proto = out.File
	file_efgs_proto_rawDesc = nil
	file_efgs_proto_goTypes = nil
	file_efgs_proto_depIdxs = nil
}
