region         = "us-central1"
project        = "covid19cz"
zone           = "us-central1-a"
instance_name  = "atlantis"
repo_allowlist = "github.com/covid19cz/erouska-backend"
image          = "runatlantis/atlantis:v0.15.1"