region         = "europe-west1"
project        = "covid19cz"
zone           = "europe-west1-b"
instance_name  = "atlantis"
instance_type  = "e2-small"
repo_allowlist = "github.com/covid19cz/erouska-backend"
image          = "runatlantis/atlantis:v0.16.0"
