#!/usr/bin/env bash
set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

gcloud builds submit "${ROOT}" \
  --project "${PROJECT_ID}" \
  --config "${ROOT}/builders/deploy.yaml"
