name: deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy erouska-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Cloud Functions
        id: deploy
        run: PROJECT_ID="$PROJECT_ID" ./scripts/deploy
